server: 
  port: 9004
spring:
  application:
    name: recruit-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.10.254:13306/tensquare_article?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: walp1314
  jpa:
    database: MySQL
    show-sql: true
  data:
      mongodb:
        host: 10.10.10.254
        database: recruitdb
  redis:
    host: 10.10.10.254
    port: 16379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true