server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 10.10.10.254
  aliyun:
    sms:
      accessKeyId: LTAIKwFq9lPHwLvh
      accessKeySecret: 不能告诉你
      template_code: SMS_149385475
      sign_name: 传智播客