server: 
  port: 9003
spring: 
  application:  
    name: recruit-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.10.254:13306/tensquare_qa?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: walp1314
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: iot4yj
    ttl: 360000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enable: true