server: 
  port: 9005
spring: 
  application:  
    name: recruit-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.10.254:13306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: walp1314
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 10.10.10.254
    port: 16379